-- ============================================
-- MIGRAÇÃO: Radar de Pesquisa + Ideias (Admin)
-- Data: 2025-12-14
-- PostgreSQL-first
-- ============================================

-- Topics (áreas/temas definidos no admin)
CREATE TABLE IF NOT EXISTS radar_topics (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(160) NOT NULL,
    descricao TEXT,
    keywords TEXT,
    idiomas VARCHAR(20) NOT NULL DEFAULT 'pt,en',
    regioes VARCHAR(80) NOT NULL DEFAULT 'br,us,eu',
    categoria_artigos_id INT REFERENCES categorias_artigos(id) ON DELETE SET NULL,
    ativo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_radar_topics_ativo ON radar_topics(ativo);

-- Sources (RSS, APIs ou scraping)
CREATE TABLE IF NOT EXISTS radar_sources (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(160) NOT NULL,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('rss', 'api', 'scrape')),
    url TEXT,
    config JSONB,
    ativo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_radar_sources_ativo ON radar_sources(ativo);
CREATE INDEX IF NOT EXISTS idx_radar_sources_tipo ON radar_sources(tipo);

-- Many-to-many: topics <-> sources
CREATE TABLE IF NOT EXISTS radar_topic_sources (
    topic_id INT NOT NULL REFERENCES radar_topics(id) ON DELETE CASCADE,
    source_id INT NOT NULL REFERENCES radar_sources(id) ON DELETE CASCADE,
    PRIMARY KEY (topic_id, source_id)
);

CREATE INDEX IF NOT EXISTS idx_radar_topic_sources_topic ON radar_topic_sources(topic_id);
CREATE INDEX IF NOT EXISTS idx_radar_topic_sources_source ON radar_topic_sources(source_id);

-- Executions (runs)
CREATE TABLE IF NOT EXISTS radar_runs (
    id SERIAL PRIMARY KEY,
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'success', 'error')),
    triggered_by VARCHAR(20) NOT NULL DEFAULT 'manual' CHECK (triggered_by IN ('manual', 'cron')),
    log TEXT,
    meta JSONB
);

CREATE INDEX IF NOT EXISTS idx_radar_runs_started_at ON radar_runs(started_at DESC);

-- Collected items (links, vídeos, podcasts etc.)
CREATE TABLE IF NOT EXISTS radar_items (
    id SERIAL PRIMARY KEY,
    source_id INT REFERENCES radar_sources(id) ON DELETE SET NULL,
    url TEXT NOT NULL,
    url_norm TEXT NOT NULL,
    titulo TEXT,
    descricao TEXT,
    snippet TEXT,
    tipo_midia VARCHAR(20) NOT NULL DEFAULT 'article' CHECK (tipo_midia IN ('article', 'video', 'podcast', 'other')),
    published_at TIMESTAMP,
    fetched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    idioma VARCHAR(5),
    regiao VARCHAR(10),
    score NUMERIC(10,2) DEFAULT 0,
    raw JSONB,
    UNIQUE (url_norm)
);

CREATE INDEX IF NOT EXISTS idx_radar_items_source_id ON radar_items(source_id);
CREATE INDEX IF NOT EXISTS idx_radar_items_fetched_at ON radar_items(fetched_at DESC);
CREATE INDEX IF NOT EXISTS idx_radar_items_score ON radar_items(score DESC);

-- Many-to-many: items <-> topics
CREATE TABLE IF NOT EXISTS radar_item_topics (
    item_id INT NOT NULL REFERENCES radar_items(id) ON DELETE CASCADE,
    topic_id INT NOT NULL REFERENCES radar_topics(id) ON DELETE CASCADE,
    PRIMARY KEY (item_id, topic_id)
);

CREATE INDEX IF NOT EXISTS idx_radar_item_topics_item ON radar_item_topics(item_id);
CREATE INDEX IF NOT EXISTS idx_radar_item_topics_topic ON radar_item_topics(topic_id);

-- Ideas generated by IA (per topic)
CREATE TABLE IF NOT EXISTS radar_ideas (
    id SERIAL PRIMARY KEY,
    topic_id INT NOT NULL REFERENCES radar_topics(id) ON DELETE CASCADE,
    titulo VARCHAR(255) NOT NULL,
    angulo TEXT,
    resumo TEXT,
    outline TEXT,
    tags TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'nova' CHECK (status IN ('nova', 'selecionada', 'descartada', 'virou_artigo')),
    source_item_ids JSONB,
    ai_model VARCHAR(120),
    ai_prompt TEXT,
    ai_raw TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_radar_ideas_topic_status ON radar_ideas(topic_id, status);
CREATE INDEX IF NOT EXISTS idx_radar_ideas_created_at ON radar_ideas(created_at DESC);

-- updated_at triggers (reuse existing function if present)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'update_updated_at_column') THEN
        DROP TRIGGER IF EXISTS update_radar_topics_updated_at ON radar_topics;
        CREATE TRIGGER update_radar_topics_updated_at
            BEFORE UPDATE ON radar_topics
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();

        DROP TRIGGER IF EXISTS update_radar_sources_updated_at ON radar_sources;
        CREATE TRIGGER update_radar_sources_updated_at
            BEFORE UPDATE ON radar_sources
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();

        DROP TRIGGER IF EXISTS update_radar_ideas_updated_at ON radar_ideas;
        CREATE TRIGGER update_radar_ideas_updated_at
            BEFORE UPDATE ON radar_ideas
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
    END IF;
END $$;

